### ISSUE TITLE
Fix detection of baremetal nodes

### ISSUE THREAD

**Issue by fwiesel** [sapcc/networking-arista#1]
Ironic changes the behaviour, that ports keep the `device_owner=compute:<az>`.
We need to integrate the following change to remove some workarounds deployed:
sapcc/networking-arista@418c436

**Comment by fwiesel** [comment]
After fixing the driver, we can solve  sapcc/ironic#1

**Comment by fwiesel** [comment]
This should be solved by #6

**Comment by notandy** [comment]
I close this since you merged it already, reopen if necessary
